import 'server-only'

import corpusJson from './corpus.json'
import type { CitationSource, Corpus, CorpusDocument } from './types'

/**
 * The chat citation corpus, generated by `pnpm build:chat-context` and
 * imported as a JSON module so it ships inside the route handler bundle.
 *
 * Server-only: the corpus is ~300kb and contains every public repo's full
 * README — never expose this to the client. Citation metadata for rendering
 * cards is sent back per-message instead.
 *
 * If this import errors, the script hasn't been run yet:
 *   pnpm build:chat-context
 */
const corpus = corpusJson as Corpus

let documentIndex: Map<string, CorpusDocument> | null = null

function buildIndex(): Map<string, CorpusDocument> {
  if (documentIndex) return documentIndex
  documentIndex = new Map(
    corpus.documents.map((d) => [d.sourceId, d] as const),
  )
  return documentIndex
}

export function getCorpus(): Corpus {
  return corpus
}

export function getDocumentById(
  sourceId: string,
): CorpusDocument | undefined {
  return buildIndex().get(sourceId)
}

/**
 * Returns the list of valid source IDs — useful for validating model output
 * against an allowlist if we ever add a DIY-citation fallback.
 */
export function listSourceIds(): string[] {
  return corpus.documents.map((d) => d.sourceId)
}

/**
 * Strips the server-only `text` field from a CorpusDocument so it can be
 * shipped to the client as a CitationSource. Discriminator preserved.
 */
export function toCitationSource(doc: CorpusDocument): CitationSource {
  if (doc.kind === 'resume-section') {
    return {
      kind: 'resume-section',
      title: doc.title,
      resumeAnchor: doc.resumeAnchor,
      section: doc.section,
    }
  }
  return {
    kind: 'repo-readme',
    title: doc.title,
    repo: doc.repo,
  }
}
